### PR TITLE
Fix issue/26

### PR DESCRIPTION
**Pull request by ekaszubski**
Ref: #26

### CODE REVIEW

**Comment by ekaszubski** [comment]
Test build 1 [released](https://github.com/semio-robotics/semio_ros/releases/tag/0.8.6-0%2Bpr28-1)

**Comment by ekaszubski** [comment]
Test build 1 [released](https://github.com/semio-robotics/semio_ros/releases/tag/0.8.6-0%2Bpr28-1)

**Comment by rossmead** [comment]
inconsistent attention markers

Really weird behavior -- the attention markers flicker with very different colors (including blue, purple, and magenta).

Also, the attention arrow (/closest/max) doesn't show up on the visualization list until after I cover my head so that the head position is not tracked; once it shows up on the visualization list, I don't ever actually see the arrow.

**Comment by ekaszubski** [comment]
Test build 2 [released](https://github.com/semio-robotics/semio_ros/releases/tag/0.8.6-0%2Bpr28-2)

**Comment by ekaszubski** [comment]
Confirmed that this works

**Pull request merged**
