### PR TITLE
Fix issue/10

### PR DESCRIPTION
**Pull request by ekaszubski**
Ref: #10

### CODE REVIEW

**Comment by ekaszubski** [comment]
Test build 1 [released](https://github.com/semio-robotics/semio_ros/releases/tag/0.7.2-0%2Bpr11-1)

**Comment by rossmead** [comment]
The software ran all day and night with no crashes, so that's a plus!  A few notes:
1. When two people are in the frame, the markers sort of flicker between colors.  If I understand correctly, this is being addressed by issue #10.
2. We're seeing that the spheres/cylinders for an additional tracked person are multiple colors for that one person at the same time (i.e., some spheres/cylinders are one color, and some spheres/cylinders are another color).  Fortunately, the first person color is consistent.  Opened issue #13 for it (will post picture later).
3. When one of the users leaves the Kinect field-of-view, sometimes joints and/or limbs are left behind in the visualization.  Opened issue #14 for it (will post picture later).
4. The deictic behavior recognition system seems to work well under rather idealistic constraints (i.e., head oriented at object and wrist on head-gaze line); however, this doesn't seem to work well in our natural tests.  Braden and I have developed an approach that we think will dramatically improve performance and is also easy to implement (it's a simple extension from the approaches that we're already using).  Details will be outlined in a separate issue, but we should discuss to make sure the approach is clear.

**Comment by ekaszubski** [comment]
@semio-robotics/all Can we verify that this works?

**Comment by rossmead** [comment]
Literally was just about to confirm that it was working, and then we had the multi-color issue again... :-/

Might be because it saw a _third_ person.  (Apparently, we are not alone... :-O)

See below.

Would it make things easier to have all of the humanoids in a single "humanoids" namespace, and then separate out attention and deixis stuff?  Alternatively, we could just make attention/deixis only show output for the closest person (I'm actually a fan of this).  Thoughts?

more multi-color person tracking

**Comment by ekaszubski** [comment]
OK, please move/add that image to #13. I think I may know what's causing it. Is everything else working (with the exception of the issues already submitted)?

**Comment by rossmead** [comment]
Added image to #13.

Also still getting the issue described in #14.  Will respond in that thread.

Very stable though.

**Comment by ekaszubski** [comment]
OK, thanks for testing, I'm going to merge this and we can address the remaining issues outside of this PR.

**Pull request merged**
