### PR TITLE
Update deixis node for new deixis implementation

### PR DESCRIPTION
**Pull request by ekaszubski**

### CODE REVIEW

**Comment by ekaszubski** [comment]
Test build 1 [released](https://github.com/semio-robotics/semio_ros/releases/tag/0.8.8-0%2Bpr30-1)

**Comment by ekaszubski** [comment]
Test build 2 [released](https://github.com/semio-robotics/semio_ros/releases/tag/0.8.8-0%2Bpr30-2)

**Comment by rossmead** [comment]
Looks good.

If head not tracked, markers go away.  Will remove that head tracked constraint wherever necessary in next version.

**Comment by ekaszubski** [comment]
> If head not tracked, markers go away. Will remove that head tracked constraint wherever necessary in next version.

In the process of fixing this now along with adding dynamic max-likelihood sources to deixis viz. Both will be included in test build 3.

**Comment by ekaszubski** [comment]
Test build 3 [released](https://github.com/semio-robotics/semio_ros/releases/tag/0.8.8-0%2Bpr30-3)

**Comment by rossmead** [comment]
Bawler -- it works perfectly.

#winning

**Comment by ekaszubski** [comment]
Confirmed that this works

**Pull request merged**
